<a href="https://colab.research.google.com/github/Nevethawei/my-first-code/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [ ]:
arr1=np.arange(1,9)
print(arr1)

[1 2 3 4 5 6 7 8]


In [ ]:
print(arr.shape,arr.ndim,arr.size,arr.dtype)

(6,) 1 6 int64


In [ ]:
print(arr[4])

5


In [ ]:
print(arr[2:])

[3 4 5 6]


In [ ]:
print(arr[0::2])

[1 3 5]


In [ ]:
print(arr[1:6:2])

[2 4 6]


In [ ]:
print(arr[3::-2])

[4 2]


In [ ]:
multi=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(multi)
print(multi.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
print(multi[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
multi=np.array([[1,2,3],[4,5,6],[7,8,9]])
ele=multi[1:3,1:3]
print(ele)

[[5 6]
 [8 9]]
